#!/usr/bin/zsh
typeset -ag SSH_KEYS
SSH_KEYS=(
          "$HOME/.ssh/id_ed25519"
          "$HOME/.ssh/global_admin_key"
          "$HOME/.ssh/BigDataCloudKey.pem"
          )

function keys {
        if [[ ! -r "$HOME/.ssh/ssh-agent.socket" ]]; then 
                eval `ssh-agent -s -a $HOME/.ssh/ssh-agent.socket` 
        fi 
        export SSH_AUTH_SOCK="$HOME/.ssh/ssh-agent.socket"


}

function rekey_keys {
        read -s "oldpassw?Password: "; echo 
        read -s "passw?New password: "; echo
        echo "$passw"

        for key in $@; do 
                if [[ -e "$key" ]]; then 
expect <<DOC
                                spawn ssh-keygen -p -f $key 
                                expect "Enter old"
                                send "$oldpassw\r"
                                expect "Enter new"
                                send "$passw\r"
                                expect "Enter same"
                                send "$passw\r"
                                expect {
                                        Your {
                                        exit 0 
                                        }
                                }

DOC 
        fi 
done 

}

function encrypt_keys {
        read -s "passw?Password: "; echo
        echo "$passw"
        for key in $@; do 
                if [[ -e "$key" ]]; then 
expect <<DOC
                                spawn ssh-keygen -p -f $key 
                                expect "Enter new"
                                send "$passw\r"
                                expect "Enter same"
                                send "$passw\r"
                                expect {
                                        Your {
                                        exit 0 
                                        }
                                }

DOC 
        fi 
done 

}

function add_keys { 
        read -s "passw?Password: "; echo

        for key in $SSH_KEYS; do
                if [[ -e "$key" ]]; then
expect <<DOC 
                       spawn ssh-add $key
                       expect "Enter passphrase"
                       send "$passw\r"
                       expect {
                         Bad {
                                puts "Wrong password"
                                exit 1  
                         }
                         Iden { 
                         exit 0  
                         }
                         eof {
                         puts "No passphrase given"
                         exit 1 
                 }

                       }
DOC
if [[ "$?" != 0 ]]; then 
        return 1
fi 
                fi
        done
}
