#!/bin/sh 

BRANCH="$1"

shift

ROOT_DIR="$(git rev-parse --show-toplevel)"
DIR_NAME="$(mktemp -u)"
THIS_DIR="$(realpath --relative-to="$ROOT_DIR" "$PWD")"

echo "Running in $THIS_DIR"

cleanup(){
        rm -r "$DIR_NAME"
        exit "$1"
}

( 
cd /tmp || cleanup 1 

git clone --single-branch --branch "$BRANCH" --shared "${ROOT_DIR}/.git" "$DIR_NAME" || cleanup 1

cd "$DIR_NAME/$THIS_DIR" || cleanup 1 

eval "$@" || cleanup 1 
cd /tmp || cleanup 1
rm -r "$DIR_NAME"

) || cleanup 0
